bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Z6OJugsMSVjNw5Egp/UZjXh1ov65yGj5qKkQ1A9sblXt/9oac74LwJNW8ewQcQBi/FUofk6JylcrVdrdiM4rmthQVER9TwCOqlyyT2VQ4mIa02j28j/YHOxltgeob3bIQ0JDXnTc+okJKetWs3Ig5PmFAUawVDeiMTwGZts3nvyCN1p1Re5HcglkSTIH2SaxRsehStN23/BD8GU8Br6wW+kw2xglWy1fuvISuolqKKv8BJlPs34nv/7tQLEpzC5MtHd2y/7L5cl2s6c9iEqemUb9qJf4csiOWCpkmFe5afEQEGa9ruCLs04SYZDQ112hYnXjuELGhXEixRa+Zczl0k9GwPI0ocU7Yw25rACHPeG7ZqA3dYSJfL5fVlXoVpLw6aGHldhcTjodblpByEUU7fqWKSBqsnWR2RatjdDM4IRaPNSjs3PRmfUKJe1jWfIKN+DaamD1aamlMjawM1PZNW3smTVzvdLcev8KhGcYibgfYQPvwayTo91oPv4LPcJ7iumSKyTu4EaAo/oQmicCWSW6L4igj/qJrSGZxXYNyiHfIyI35FUHF7raLIKzxHOu1zNgNfeTt9172MlrEFY12Jip77kgueRIfv2cRAvpGcnwOw6s2DtCPOkYKn5Eih1GzbNh3IwLpoBpazGNCrRsUCY3WL17ToxGuzJZf8m8q8Y=
conda_forge_output_validation: true
